### ISSUE TITLE
Fix failing travis test

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/tenacious#102]
https://travis-ci.org/emerald-rubies/tenacious#L606

Webpacker requires Yarn version >= 0.20.1. Please download and install the latest version from https://yarnpkg.com/lang/en/docs/install/

**Comment by troystarwalt** [comment]
I came across this problem on a project I started last week. Below is my install block in `.travis.hml`.

```
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
```

Adding that fixed the failing travis test for me.

**Comment by pachonk** [comment]
I'm guessing that changed the container base and that's what's causing the
issue. bin/setup takes care of a lot of that, but before that step, simply
line 5 might fix it. On automated things, please use the explicit "install"
though.

**Comment by pachonk** [comment]
@troystarwalt Were you offering to fix this or just pointing to a possible fix?
