### ISSUE TITLE
Add pry-rails to the Gemfile

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/tenacious#108]
Please add `pry-rails` and `pry-byebug`, thanks!

**Comment by Exellin** [comment]
What does this do and why do you want it?

**Comment by pachonk** [comment]
Allows you to do `binding.pry` to stop code execution and inspect things in real time. Switches rails c from irb to pry.

**Comment by Exellin** [comment]
Is this an alternative to debugger?  If so anything it does better?

**Comment by pachonk** [comment]
There _is_ pry-debugger, but it's an interactive ruby env that has more power. Can cd into objects, ls their methods, etc.

**Comment by Exellin** [comment]
Since you just saw what I can do with debugger, are there any other features which pry-rails does that debugger doesn't have?  Or am I still misunderstanding what pry does in the context of 'stop code execution and inspect things in real time'.

**Comment by pachonk** [comment]
It's the tools pry rails and pry byebug have that makes it powerful.
_ is a variable that gives you the last returned value
$ method_name gives you the code of that method.
cd Object changes into the object
ls lists methods available within the current context.

**Comment by Exellin** [comment]
ok sounds cool to install and try out.

**Comment by pachonk** [comment]
I like pry-rails and pry-byebug together.
Game for making this a real issue for a greenie to install?

**Comment by Exellin** [comment]
yeah

**Comment by pachonk** [comment]
Please add `pry-rails` and `pry-byebug`, thanks!
