### ISSUE TITLE
Create Inventory Model

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/tenacious#11]
This will be the model to encapsulate all the items into 1 group. This is the level where user permissions will be applied.
Need a name and description for now, we'll connect it to users later.

**Comment by Exellin** [comment]
I'll work on this right now

**Comment by Exellin** [comment]
going by your piece of paper you called it item and it has 6 properties.  So we are just using 2 of those properties for now?  And we'll call the model inventory/inventories?

**Comment by pachonk** [comment]
I need to redraw paper. There's a small change here to allow 1 server for many people to sign up and each inventory will eventually require the admin of that inventory to add the user as a role in each inventory.

**Comment by Exellin** [comment]
ok should I wait for your to redraw it or go ahead and create a simple model with the name and description properties?

**Comment by pachonk** [comment]
Creating it with current attributes is fine.

**Comment by Exellin** [comment]
do we want character limits on the name and description?

**Comment by pachonk** [comment]
Use VARCHAR 255 and TEXT on description. I'd say.

**Comment by Exellin** [comment]
isn't text meant for longer strings, what is wrong with a string here?  also I need to quickly look up what varchar is and how to implement it.

**Comment by pachonk** [comment]
description could potentially be many, many lines were my thought. (string is fine instead of varchar)

**Comment by pachonk** [comment]
`t.string :name, :limit => 255`

**Comment by pachonk** [comment]
We could make description feel more like a bio and limit to 255 though.

**Comment by pachonk** [comment]
And make name a little shorter, perhaps.

**Comment by Exellin** [comment]
so for these limits in the database will it produce model errors if the user tries to create a description with more than 255 characters?  Or do we also have to limit it within the model file?

**Comment by Exellin** [comment]
also the text type isn't being assigned the limit in the schema like the string

**Comment by Exellin** [comment]
So I'll keep the text field unrestricted in the schema since it isn't applying anyway unless we want to limit it to a 255 character string.  then we can limit the length of the description in the model.

**Comment by pachonk** [comment]
You'd use string again if you wanted to limit to 255.

**Comment by pachonk** [comment]
If you limit at the DB level, you should also include a validation for that field as well, within the model (and also on the frontend)

**Comment by Exellin** [comment]
ok so the db check is just extra security.

**Comment by Exellin** [comment]
I could set a quick limit of like 1000 characters for description.  255 seems very short for a multiple sentence/paragraph field.

**Comment by pachonk** [comment]
DB check is a hard limit to ensure the DB matches expectation.
Model check is to prevent hitting the DB if invalid.
Front end check is to prevent a request to the server at all.

**Comment by pachonk** [comment]
What I was trying to say is that description could be like github's org description too, which is limited to 255 I think

**Comment by Exellin** [comment]
ok then it should also be a string if it is limited to only 255 characters right, which is fine we want that.

**Comment by pachonk** [comment]
Yep

**Comment by pachonk** [comment]
I think string == varchar btw. I'd have to look to verify.
