### ISSUE TITLE
Which authorization gem should we use?

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/tenacious#12]

**Comment by Talha5** [comment]
I think we should use Pundit because of its structure.

**Comment by pachonk** [comment]
We might not even need one, but there are plenty out there. cancan and pundit come to mind.

**Comment by Talha5** [comment]
in that case we can use rails enums too if we dont have too many rights and roles for users.

**Comment by pachonk** [comment]
@Talha5 I have reasons to say NEVER use enums... But yeah, we can do something similar.

**Comment by pachonk** [comment]
We'll have more we want to add, and if you plan on it changing... You really shouldn't use enum imho. We should have a vid call to discuss all the reasons.

**Comment by sanchez2210** [comment]
I also think Pundit is a good option!

**Comment by pachonk** [comment]
But is pundit the best option? If so, why? What other options are out there?

**Comment by sanchez2210** [comment]
It has a good structure that's very self explanatory. Cancancan is another option

**Comment by pachonk** [comment]
So what makes pundit STAND OUT from all the others?

**Comment by sanchez2210** [comment]
I think both of them are simple enough, but Pundit does seem to be closer to a DIY authorization engine. No DSL as well

**Comment by pachonk** [comment]
Then the last question: Do we actually need an authorization gem?

**Comment by sanchez2210** [comment]
I'm not sure to be able to answer that question.

**Comment by pachonk** [comment]
Understood. Just all questions worth asking.

**Comment by pachonk** [comment]
Looks like an auth lib would be overkill for now.
