### ISSUE TITLE
As an inventory administrator, I want to be able to associate a user to an inventory at the level or read, write, and admin

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/tenacious#17]

**Comment by Exellin** [comment]
So If i understand what is going on here when a user creates an inventory, a relationship will be made between the two and the user will have access to read and write that inventory.

Then administrators will have the power to associate additional users to the inventory in order to give more users read and write access towards it.

**Comment by pachonk** [comment]
admin would mean they have administrative rights over that "Inventory" they can change the name, desc, users allowed on repo, etc.

**Comment by sanchez2210** [comment]
Do you think a HABTM is the way to go? I have some experience with them and came to the (maybe erroneous) conclusion that there's nothing a HABTM relationship will provide that a Has_many, Through: will not.

**Comment by Exellin** [comment]
has_many, through: requires setting up an additional model and is preferred if you want to add any extra attributes to the relationship (such as a status etc).  HABTM is the same thing only slightly simpler to set up.  I'm not sure if it is best practice to always use has_many ,through: as it allows the flexibility of adding additional attributes in the future and accomplishes the same thing as HABTM.

**Comment by sanchez2210** [comment]
Yes, that's my point. Also it's so much easier to add relationship validations on the join model. Specially at nested forms

**Comment by pachonk** [comment]
I personally default to HABTM unless I need additional attributes, since it avoids setting up a model that's probably going to be mostly blank.
If I need to add additional attributes, that's when I convert it to a `has_many through:`

**Comment by sanchez2210** [comment]
Okay, only that for new devs like me it's usually hard to know when exactly is recommended to turn it into a `has_many, through:` ( mostly As soon as some extra attributes on the relationship is needed ) and delay the switch too long ( I did, HM-T looked scary )

**Comment by pachonk** [comment]
The simple answer is "when you need to have a model to back the intermediate table" the good news is you have 3 professional developers to help you make the call when it's ready to be converted to a has_many through.

**Comment by sanchez2210** [comment]
Great, I will make the additions now.

**Comment by sanchez2210** [comment]
#29

**Comment by Exellin** [comment]
What additions are you making right now @sanchez2210?  @troystarwalt is already making the relationship in issue #29

**Comment by sanchez2210** [comment]
Yeah, I checked through the issues and noticed that there was work already being done there.

**Comment by Exellin** [comment]
I'm working on this at the same time as #29

**Comment by Exellin** [comment]
How do we want to associate additional users to the inventory?  Should an inventory administrator have search box to look for other users, they select the user and the level they want to associate them on and click invite?  Then the user will get an invitation on their dashboard they can accept?

That's my first thought on doing this.
