### ISSUE TITLE
As an organization, I want to be able to add an inventory

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/tenacious#18]
That inventory should be automatically associated with that org.

**Comment by dendenvitorio** [comment]
once @DanBonehill is done, I think I wanna pick this up

**Comment by pachonk** [comment]
@dendenvitorio How about #16 instead? Need to be able to add an org and such prior to this issue, so it might be a week or so.

**Comment by dendenvitorio** [comment]
Oops #16 was already gotten by luis. Forgot to put my comment there though, anyways I'll work on this

**Comment by DanBonehill** [comment]
I'll pick this up.

**Comment by pachonk** [comment]
@DanBonehill this and #16 go hand in hand. Can probably knock out both in 1 PR.

**Comment by DanBonehill** [comment]
I think @sanchez2210 has picked that one up

**Comment by pachonk** [comment]
Okay. Then might want to coordinate with him on this issue.

**Comment by DanBonehill** [comment]
So I'm struggling to understand how this would work.

You never sign in as an organization, only users sign in, so would they be creating an inventory on behalf of an organization they belong to?
