### ISSUE TITLE
set habtm relationship between user and inventory

### ISSUE THREAD

**Issue by Exellin** [emerald-rubies/tenacious#29]

**Comment by pachonk** [comment]
Related to: #17

**Comment by Exellin** [comment]
I created this issue as it needs to be implemented before we move on to #16 (which requires a controller and view) or 17 which you referenced already.  Or would it be better to create a pull request saying it as a partial implementation of those issues?

**Comment by pachonk** [comment]
In that case, I put in this issue's description "Required for #16"

**Comment by troystarwalt** [comment]
I'm working on this, but needed to add the defaul_url from #38 before finalizing the HABTM.

**Comment by Exellin** [comment]
This can be closed now.

**Comment by Exellin** [comment]
@troystarwalt are you working on this right now or still busy with family atm?

**Comment by troystarwalt** [comment]
All yours!

**Comment by Exellin** [comment]
This can be closed now.
