### ISSUE TITLE
Add ruby version

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/tenacious#30]
I use `asdf` for both node and ruby, so I like `.tool-versions` but I'm guessing not everyone is.
We can either all move to `asdf`, which I don't expect everyone to do, or add the `.ruby-version` and the equal for node.

**Comment by sanchez2210** [comment]
I think many will be already using .ruby-version and it should be easy to go with that for now.

**Comment by pachonk** [comment]
@sanchez2210 Do you want to add it?

**Comment by sanchez2210** [comment]
Sure.

**Comment by sanchez2210** [comment]
@emerald-rubies/emeralds we'll be using -v 2.4.1 is that good for you?

**Comment by pachonk** [comment]
Yep, 2.4.1 is the version we will be using. If anybody needs help setting up a version manager, I can help you out.
