### ISSUE TITLE
Create administrators, either through a boolean in the devise user model or as another model entirely

### ISSUE THREAD

**Issue by Exellin** [emerald-rubies/tenacious#31]
I prefer to just apply a boolean to the user model and then surround each administrator action in an if statement checking if the user is an administrator.

**Comment by pachonk** [comment]
@Exellin This is a little misleading. This makes it sounds like we want admins on the overall system, while I think we probably want to have admins on the level of repos and orgs. I propose that we hold off on "implementation issues" and stick to "user story" issues to make sure our implementation matches our stories requests.

**Comment by Exellin** [comment]
Ok so we want an organization called "administators" with certain abilities.  My mistake on the misunderstanding.  Probably would be best to close the issue then if we are never going to implement administrators on this level.

**Comment by pachonk** [comment]
Uhh, more like if I create an organization, see #17 
For now, assume that the client doesn't want there to be "super admins" that have control over the entire system until later.
