### ISSUE TITLE
As a user, I want the main page to present a CTA to sign up/log in

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/tenacious#32]

**Comment by DanBonehill** [comment]
I'll work on this.

Will add root route and call to action. Do we have Bootstrap or anything installed? If not, are we using it or something similar?

**Comment by troystarwalt** [comment]
I don't think we've talked about the frontend much. We certainly want the site to look good, and I'm not sure we want to spend too much time doing anything from scratch.

So, I think Bootstrap would be fine. Other options: Foundation, Bulma, Material

Anyone have a preference or argument for one over the others?

**Comment by DanBonehill** [comment]
Personally Bootstrap would be _easier_ as it's the only one I've used before, but I'm happy to use whichever if there are benefits to others that are out there.

**Comment by DanBonehill** [comment]
Ok so I've finally got my setup working. A few questions for this story:

1. If I create the root route, I need to give it a controller. Normally I'd create a PagesController and then have the root route go to the index action. Is this approach ok, or is there another way I should do this?
2. What tests should I create for this? Request, View, Controller, Feature? A mixture?

**Comment by pachonk** [comment]
We are going for a VERY vanilla outline for this first project. The most I would personally be willing to use is a mixin lib like bourbon.io or comparable softwares.

**Comment by pachonk** [comment]
I feel Pages controller is a little generic. Is there maybe a way to name the controller in order to specify that "All routes within the controller are within the "you don't have to log in" section of the site" IE if we added an "about us" piece.
So what can we name it to make it more clear that the entire controller is made to be unauthed
