### ISSUE TITLE
stick to one naming convention for factories.

### ISSUE THREAD

**Issue by Exellin** [emerald-rubies/tenacious#39]
At the moment we have inventory.rb (singular) and users.rb (plural).  We should stick to one and maybe even append the file with _factory.rb

**Comment by troystarwalt** [comment]
Good point. Shouldn't the factories match the model that it is referencing?

**Comment by Exellin** [comment]
Yeah that's how I have done it in my past projects.  So we would just need to change users.rb to user.rb

**Comment by pachonk** [comment]
Factories are plural.
`rails g model test` and look at the GENERATED factory (or maybe we need to turn factory generation on) I believe factories are always plural.

**Comment by DanBonehill** [comment]
The factory that was created when I generated the Organization model was plural.

**Comment by pachonk** [comment]
^^

**Comment by Exellin** [comment]
ok I'll make a quick fix on inventory.rb
