### ISSUE TITLE
add organization model

### ISSUE THREAD

**Issue by Exellin** [emerald-rubies/tenacious#41]
## In Model
has a name attribute which is required, limited to a string of 255 characters, and is unique.

has_many inventories
HABTM users.

## In Schema
The name attribute will be not null and have a limit of 255.

Create table organization_users with organization id and user id with both indexed.

Needed for: #18 #19

**Comment by DanBonehill** [comment]
I could pick this up, the model would look something like:
```
validates :name, presence: true, length: { maximum: 255 }
has_many :inventories
has_and_belongs_to_many :users
```
Would I need to create a table called organization_users to link the both, or do you only need this when using has_many :through?

**Comment by Exellin** [comment]
you still need to create the table in the schema.  Rails isn't that magical

**Comment by DanBonehill** [comment]
Haha. I'll work on it now

**Comment by Exellin** [comment]
also the organisation name should be unique.

**Comment by pachonk** [comment]
and not null

**Comment by DanBonehill** [comment]
Just to check, as it's not specified above.

If Organization has_many Inventories, does Inventory belong_to Organization?

**Comment by pachonk** [comment]
belongs to org OR user

**Comment by DanBonehill** [comment]
Ok, so do I need to add both of these as part of this story?

So add the below to the Inventory Model
`belongs_to :organization, :user`

**Comment by DanBonehill** [comment]
This is now done, tests pass. I haven't updated the Inventory Model as I wasn't sure if it was in scope of this issue. Let me know if it is and I'll make the change there.

**Comment by pachonk** [comment]
Nah, INVENTORY user stories will update this piece.

**Comment by DanBonehill** [comment]
Ok, so I've just added `has_many :inventories` to the Organization model and that's it. In which case, I believe this is ready to be merged.
