### ISSUE TITLE
As a user, I would like to see a navigation bar on all pages with links to every view in the webpage.

### ISSUE THREAD

**Issue by Exellin** [emerald-rubies/tenacious#55]
Things to discuss:

- How should we collapse the navbar (hamburger icon or navbar increases in height to encompass links going on to new line)

- Navbar stays fixed at top of screen, disappears on scroll down then reappears when scrolling up, or is transparent when scrolling down etc)

- Color of links, styling on hover (link changes color, a bar is put underneath or on top of the link etc)

- Which links to group and which to have in a dropdown (eg for authorization see both sign up and sign in, or have a dropdown which shows both options)

- Are we creating a logo of some kind to put in the navbar.

- Which links should float to the left, stay in the center, or float right.

Any other things we want to implement for the navbar initially.

**Comment by DanBonehill** [comment]
Are we doing all of this with vanilla CSS?

**Comment by Exellin** [comment]
yeah.  I can do it if no one else wants to I've made a few navbars with vanilla css.

**Comment by Exellin** [comment]
Working on this now.

**Comment by pachonk** [comment]
I'd love to see the logged-in to look a lot like Github's navbar. Nice, clean, simple.

**Comment by Exellin** [comment]
At the moment we don't have avatars or usernames, so right now I'm thinking just a dropdown that starts with 'Your Profile' and Log out as an option.

For things like your organizations, your inventories etc, do we want those on the navbar or will we eventually add them to the dropdown under your profile.

**Comment by pachonk** [comment]
I'm almost thinking that the only way to navi to your org/inv is via your dashboard. Not sure what's nicest for UX.

**Comment by Exellin** [comment]
I think at the moment we can have all links directly on the navbar, and then if it gets too cluttered we can add it to a dropdown (or maybe just change it to a dropdown on mobile).  Dropdowns are nice to reduce clutter but add 1 extra click to user experience.

As for being able to navigation to your orgs/inventories, I'm a believer in being able to get anywhere on the application from the navbar and not having to navigate through other pages (at least for small applications like this).

**Comment by Exellin** [comment]
Alex Idea:

Instead of a hamburger icon, have a star which links to your favorited inventories etc

Have 1 or 2 other links linking to dashboard/home or both.
