### ISSUE TITLE
As a developer, I want to be able to find key documentation in a unified place (README.md)

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/tenacious#58]
Some things that need to be included:

- [ ] TravisCI Badge
- [ ] main heading "tenacious"
- [ ] under heading, at the very least the project tagline
- [ ] initial developer setup (running bin/setup, how to start the server(s), etc)
- [ ] how to run the test suite, rubocop, brakeman

**Comment by pachonk** [comment]
This might be right up your alley, @dendenvitorio

**Comment by mandyreal** [comment]
@pachonk, @dendenvitorio. - claimed this issue. created the initial readme, PR coming up soon.

**Comment by pachonk** [comment]
I got this now.
