### ISSUE TITLE
Add mobile viewport to application.html.erb

### ISSUE THREAD

**Issue by Exellin** [emerald-rubies/tenacious#62]
\<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">

This will set the width of the document equal to the width of the viewing device whether that is a desktop or phone.  If you look at the page now on a mobile device (you can do this on chrome by going into developer tools and clicking on the image with 2 devices left of elements) you'll notice that everything is zoomed out in order to fit everything on the page.

**Comment by pachonk** [comment]
Maybe explain to people that don't know what this does.
