### ISSUE TITLE
As a user, I would like to read text that has a nice font face

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/tenacious#77]

**Comment by dendenvitorio** [comment]
Roboto.

**Comment by pachonk** [comment]
I'm also a fan of roboto, but there's probably a better choice. Let's implement roboto for now since I can't stand serif font faces.

**Comment by pachonk** [comment]
Use google fonts for this

**Comment by jeison24** [comment]
@pachonk I did that issue, I added the link google font reference to `application.html.erb` and added the rule `html, body { font-family: 'Roboto', sans-serif; }` to `app/assets/stylesheets/application.scss`  is it all for this issue?

**Comment by pachonk** [comment]
For now, yep

**Comment by Exellin** [comment]
@pachonk @jeison24 I think you should put it into app/javascript/stylesheets/custom.scss instead

**Comment by jeison24** [comment]
@Exellin ok, no problem. I am going to do that

**Comment by pachonk** [comment]
I usually make a fonts partial

**Comment by Exellin** [comment]
just fonts.scss or what is a fonts partial?  And does this need to be assigned to both html and body or just body or html?
