### ISSUE TITLE
Install Devise

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/tenacious#9]
I'd say call the model "user".

**Comment by Exellin** [comment]
go ahead and tackle this if you like @sanchez2210 I just wanted to quickly get back to where we were on the last repo and I'm going to bed.

**Comment by pachonk** [comment]
Let's go 100% vanilla on Devise and we'll add/remove the features as new issues after further discussion.

**Comment by Talha5** [comment]
So, we need no `roles` for user, right? and this issue dictates simple devise installation, so i should stick to it only. And of-course no specs for devise.

**Comment by pachonk** [comment]
@Talha5 Literally follow docs word for word and use "user" and it should get done what we need for now! :)

**Comment by pachonk** [comment]
The one thing I like to see for ease of dev is factory for all models.

**Comment by sanchez2210** [comment]
Should this be closed?
