### ISSUE TITLE
General issues with this repo.

### ISSUE THREAD

**Issue by MaxPleaner** [emerald-rubies/tenacious#92]
First off, what in the hell is this even? The README has nothing to indicate what it is, nor how it's built.

Also, I see what you're trying to do with the issues page, but it doesn't really rub me the right way. It seems like these kind of statements (As a "X", I want to "Y") should be put inside a Cucumber test suite, not in the issues page. It'd be better, in my opinion, if the issues page was reserved for bugs or big pieces of desired functionality, but if you make a different issue for each minor thing you want to accomplish, it will get a little overwhelming. It's almost like you're trying to do TDD via the issues page.

**Comment by pachonk** [comment]
Hi @MaxPleaner, thanks for taking interest in this repository!
We have an issue open to make a README here: https://github.com/emerald-rubies/tenacious/issues/58 and PRs are welcome!
The issues are small and bite size to allow even the most green developer (with some help) to be able to contribute. If you have a better suggestion on how to make these issues bite size, we're all ears.

**Comment by pachonk** [comment]
Without further response, I am closing this issue. If you have any other questions, feel free to reply.
